### ISSUE TITLE
Question and/or Feature request: Populating associated Models

### ISSUE THREAD

**Issue by jegodwin** [andypike/rectify#12]
Is there an easy way to do this? I'm racking my brain over this and can't figure it out.

I have a Rectify form called `DivisionForm` with the following attribute:
 `attribute :division_species, Set[DivisionSpecies]` 

I can use this to Create the Division model and each associating `DivisionSpecies` model, but updating it isnt so easy. (FYI: a `Division` :has_many `DivisionSpecies`, so it's a collection)

When I call the Division model using the `from_model` method, I get the attributes for the `Division`, but the DivsionSpecies attribute just return an empty `Set{}` param.

Any ideas on how to setup a Rails form builder to work with this? And, is there a possible feature that  could built into Rectify to help with this?

**Comment by andypike** [comment]
When it comes to updating the model, is anything working or is it just the `DivisionSpecies` that aren't populating? It might be that you need to add a hidden `:id` field to the form builder for each `DivisionSpecies`.

I'll take a look at populating the Form Object `Set`, let me see if I can sort out an example for you.

**Comment by jegodwin** [comment]
Yeah, it's just the `DivisionSpecies` that aren't populating. on the BetterErrors page console, if I check what `@form` gives me, it shows all the correct attributes, but `DivisionSpecies` is just an empty `Set{}`.

An example would be awesome if you have time! I'm trying to populate it with a `select_tag`.

**Comment by andypike** [comment]
Yeah, looks like populating the form object has a bug in it in this case. I've just written a spec to check it and it fails so I'm working on a fix for that now. I'll take a look at populating the model afterwards with an example 😄

**Comment by jegodwin** [comment]
Thanks so much @andypike. I'm not super experienced at this level of stuff, but let me know if I can help. 

I can even add you to my repo if you want to test it in my use case.

**Comment by andypike** [comment]
Hi @jegodwin, I've got a fix for the populating of the Form Object. It's not merged in yet as I need to refactor it (as it's really ugly). If you want to try it out then the PR for it is here: https://github.com/andypike/rectify/pull/13 just update your Gemfile with:

```
gem "rectify", :github => "andypike/rectify", :branch => "populate_model_has_many"
```

Hopefully it should fix that issue as the specs are passing now. Please let me know how you get on. I can look at populating the model next.

Thanks for the help and feedback :heart:

**Comment by jegodwin** [comment]
Sounds good. I'm going to give it a shot in just a few.

I'm glad to help!

**Comment by jegodwin** [comment]
Yep! I can further confirm that the Form Object is definitely getting populated for me as well.

Thanks for the quick progress on this @andypike and good luck on the refactor.

Going to try and fix my populating my model now, and I'll let you know if I get it from here.

**Comment by jegodwin** [comment]
Whew...happy to report that I also figured out populating my model.

I think part of it was the Form Object not populating the `Set`, but you also pointed out the `hidden_field_tag` for `:id` that was needed as well.

Very thankful for all of your work on this gem and the support for it thus far! 💯

**Comment by andypike** [comment]
@jegodwin Rectify 0.4.1 has now been release with this improvement. Thanks again for the feedback and help testing :heart:

**Comment by jegodwin** [comment]
Great, thanks!
