### ISSUE TITLE
Rectify::Policy

### ISSUE THREAD

**Issue by sveredyuk** [andypike/rectify#24]
What about to add policy layer ? Class that knows the answers for all questions > `predicates?` methods. Something like `ProductPolicy.destroy?(product) #=> true/false `

I can contribute this if need.

P.S. This lib is awesome. For sure will use it for my next pet project. Thanks a lot for your approach.

**Comment by biow0lf** [comment]
Why not use just ```pundit```?

**Comment by sveredyuk** [comment]
Same as why don't use just Virtus or Draper. Rectify collect a set of good patterns. I think in this chain still missed policies and repositories.

**Comment by andypike** [comment]
Thanks for the suggestion @sveredyuk and glad you are liking the project.

Regarding policies, I personally use either `pundit` or a plain Ruby object depending on the project. At this point I would like to keep the gem relatively lean and only add functionality that doesn't already have a lightweight solution. 

This might be something that changes in the future, and maybe some documentation and examples might be something worth doing. 

Thanks again for the suggestion, if you have anymore then feel free to post them!

❤️  💛  💙  💚  💜
