### ISSUE TITLE
Where to perform authorization?

### ISSUE THREAD

**Issue by joerichsen** [andypike/rectify#26]
I was just wondering. Where does authorization fit in in the rectify stack?

On the project I am currently working on, we use Pundit. Authorization is performed in the controller between populating the model with form data and saving the model.

Ie. something like this

```
def create
    @form = RegistrationForm.from_params(params)

    authorize(@form)

    RegisterAccount.call(@form) do
      on(:ok)      { redirect_to dashboard_path }
      on(:invalid) { render :new }
      on(:already_registered) { redirect_to login_path }
    end
  end
```

Are other people using the same approach?

**Comment by andypike** [comment]
Hi @joerichsen,

Thanks for the question! First off, there isn't a built-in way in the Rectify stack to handle authorisation. Currently, I do exactly as you describe above but authorising in the controller and only running the command if that passes.

However, I have been thinking about this lately and have been wondering if we should add something explicitly. At the moment, I'm not sure. I guess it would make sense to have this as part of the Command, so we can ensure they are only run if authorised but I haven't really thought that deeply about it.

What do you think?

**Comment by joerichsen** [comment]
I think I prefer having the controller responsible for initiating the authorization. And Pundit has good support for that, so from my point of view there is no need to add it to Rectify.

But that's just my two cents :-)
