### ISSUE TITLE
Future of Virtus+Rectify

### ISSUE THREAD

**Issue by pascalbetz** [andypike/rectify#31]
Hello Rectify

Since Form Objects are based on Virtus and Virtus is not supported anymore by Solnic I was wondering what the plans are in this area. Could dry-* become a replacement for virtus?

Thanks.

**Comment by andypike** [comment]
That's a fair question and I haven't really given it a lot of thought to be honest. I know Solnic is not personally maintaining Virtus any longer but looking at the project there are some others still committing an talking about releasing new versions.

I'm not opposed to using something like dryrb and keep that change hidden from the public interface. For now I'm going to see what happens and will replace it if I feel we need to.

Thanks for the question and interest in Rectify! 💖

**Comment by pascalbetz** [comment]
Thanks for the prompt reply.
