### ISSUE TITLE
Passing view context to presenter in tests

### ISSUE THREAD

**Issue by kimberger** [andypike/rectify#5]
Hi @andypike !

Quick question. How can I test presenters that rely on view context? My test is failing because the path helpers are undefined for the presenter in the test. They work fine in the browser.

```
Failure/Error: "#{ hospital.name } - #{ link_to 'View', hospital_path(hospital) }"

     NoMethodError:
       undefined method `hospital_path' for #<DeaneryPresenter:0x007fe0afcca1b8>
```

I've tried adding `include ActionView::TestCase::Behavior` and using `.for_controller(controller)` in the spec file but then it complains that the methods defined in my presenter are undefined for the controller
```
undefined method `map_markers' for #<ActionView::TestCase::TestController:0x007fbc48b135d0>
```

Thanks in advance for any help! :)

It will work if I explicitly include everything in the presenter:
```
class DeaneryPresenter < Rectify::Presenter
  include Rails.application.routes.url_helpers
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::TagHelper
```

**Comment by andypike** [comment]
Hi @kimberger 

Sorry for the delay in getting back to you. You shouldn't need to add those modules to the presenter. The presenter uses `#view_context` of the controller passed in `#for_controller` for all methods that it doesn't know about (via `method_missing`).

If you take a look at the specs in this repo for the presenter there is an example that will use the routing helper methods: 

https://github.com/andypike/rectify/blob/master/spec/lib/rectify/presenter_spec.rb#L25

and the controller it uses is here:

https://github.com/andypike/rectify/blob/master/spec/fixtures/controllers/empty_controller.rb

Does that help? If not, do you have a branch I can look at to help you out?

Andy
