### ISSUE TITLE
Support for Rails 5

### ISSUE THREAD

**Issue by jegodwin** [andypike/rectify#9]
Note: I'm just offering some notice here since I'm using a forked version of this gem.

Aside from updating the dependency list to include ActiveRecord, ActiveModel, and ActiveSupport versions greater than 4.2, the `with_indifferent_access` method is deprecated in Rails 5.
- https://github.com/andypike/rectify/blob/master/lib/rectify/form.rb#L9

If I come across any other Rails 5 specific issues, I'll make notes here.

Thanks for this awesome gem!

**Comment by andypike** [comment]
Thanks for the heads up @jegodwin, I'll be taking a look at Rails 5 shortly :heart:

**Comment by jegodwin** [comment]
:ok_hand:

**Comment by andypike** [comment]
@jegodwin I've added a branch which fixes the issues you have raised. The PR is here: https://github.com/andypike/rectify/pull/11 would you mind taking a look at this branch to see of it works for you? Thanks

**Comment by jegodwin** [comment]
I'd be happy to do so @andypike. I'll check this out now and report back.

**Comment by jegodwin** [comment]
Yep, things seem to be working on my end; no issues here.

Thanks for the update!

**Comment by andypike** [comment]
Merged PR #11 so closing this issue.

**Comment by andypike** [comment]
Released 0.4.0 with Rails 5 support 😄
